#!/usr/bin/env python3
import random
import colors as c
author="jajaio"
"""TODO
Nothing, atm
"""
def foeattack():
    print("Your foe strikes you!")
    Player.hp=Player.hp-10
def foeheal():
    if Foe.heals<1:
        print("Your foe tried to heal, but attacked instead!")
        Player.hp=Player.hp-10
    else:
        print("Your foe Heals")
        Foe.hp=Foe.hp+35
        Foe.heals=Foe.heals-1
class Char():
    hp=None
    heals=None
class Player(Char):
    pass
class Foe(Char):
    pass
class Tank(Player):
    hp=150
    heals=2
class Mage(Player):
    hp=50
    heals=6
class Hero(Player):
    hp=100
    heals=3
class Jaja(Player):
    hp=9001
    heals=9001
class Efoe(Foe):
    hp=50
    heals=1
class Mfoe(Foe):
    hp=100
    heals=2
class Hfoe(Foe):
    hp=150
    heals=3
class Jfoe(Foe):
    hp=9001
    heals=9001
def ai():
    listy=[foeheal,foeattack]
    move=random.choice(listy)
    if move==foeheal:
        foeheal()
    elif move==foeattack:
        foeattack()
    else:
        input("Fatal Error")
def fight():
    while True:
        if Player.hp < 1:
            input("You lost!")
            break
        elif Foe.hp < 1:
            input("You win!")
            break
        else:
            print(c.clear)
            print("PLAYER HP =",Player.hp,"PLAYER HEALS =",Player.heals)
            print("FOE HP =",Foe.hp,"FOE HEALS =",Foe.heals)
            q=input("Attack(1) or Heal(2)? >>>").strip().lower()
        if q=="1":
            print("You attack your foe!")
            Foe.hp=Foe.hp-10
        elif q=="2" and Player.heals<1:
            print("You are out of heals, you attack instead.")
            Foe.hp=Foe.hp-10
        elif q=="2":
            print("You decide to stay back and heal.")
            Player.hp=Player.hp+35
            Player.heals=Player.heals-1
        ai()
def difi():
    lawl=input("Would you like to play Easy(1), Medium(2), or Hard(3)?").strip()
    if lawl=="1":
        Foe.hp=Efoe.hp
        Foe.heals=Efoe.heals
        input("You have chosen Easy! (Press enter to start the game)")
        fight()
    elif lawl=="2":
        Foe.hp=Mfoe.hp
        Foe.heals=Mfoe.heals
        input("You have chosen Medium! (Press enter to start the game)")
        fight()
    elif lawl=="3":
        Foe.hp=Hfoe.hp
        Foe.heals=Hfoe.heals
        input("You have chosen Hard! (Press enter to start the game)")
        fight()
    else:
        print("I'm sorry, please try again.")
        difi()
def selec():
    print(c.clear)
    print("Welcome to fight your foe!")
    lolint=input("""
    Would you like to play as the Warrior, Hero or Mage? (type 'stats' to well.... see the stats!) >>>
    """).strip().lower()
    if lolint=="stats":
        input("Warrior HP = "+str(Tank.hp)+" Warrior Heals = "+str(Tank.heals)+" Mage HP = "+str(Mage.hp)+" Mage Heals = "+str(Mage.heals)+" Hero HP = "+str(Hero.hp)+" Hero Heals = "+str(Hero.heals))
        selec()
    elif lolint=="jaja":
        input("You have chosen the secret class, Jaja!")
        Player.hp=Jaja.hp
        Player.heals=Jaja.heals
        difi()
    elif lolint=="warrior":
        input("You have chosen the class, Warrior!")
        Player.hp=Tank.hp
        Player.heals=Tank.heals
        difi()
    elif lolint=="mage":
        input("You have chosen the class, Mage!")
        Player.hp=Mage.hp
        Player.heals=Mage.heals
        difi()
    elif lolint=="bobe":
        input("No one likes you, Bobe.")
        selec()
    elif lolint=="hero":
        input("You have chosen the class Hero!")
        Player.hp=Hero.hp
        Player.heals=Hero.heals
        difi()
    elif lolint=="kiki":
        input("DINK")
        selec() 
    elif lolint=="dfk":
        input("Get outa mah swamp, bish.")
        selec()
    elif lolint=="ebo":
        input("Ebo is loaf, Ebo is life. All praise our great god, Ebo.")
        selec()
    else:
        input("I'm sorry, please try again.")
        selec()
selec()
