#!/usr/bin/env python3

from player import Player
import monster as m
class Game():
    def __init__(self):
        print('Welcome to the game')
        self.player=Player()
    
    def run(self):
        self.player.show_stats()
        while True:
            self.player.show_stats()
            action=input('What do you wanna do?')
            if action=="stats":
                self.player.show_stats()
            elif action=="save":
                pass
            elif action=="exit":
                input("Bye!")
                exit()
            elif action=="monster":
                count=1
    def pick_monster(self):
        count=1
        for monster in m.monsters:
            pickstr=c.base3+"{}. "+c.random_color()+"{}"+c.reset
            print(pickstr,format(count,monster.title))
            monster.show_stats()
                
    

if __name__=='__main__':
    agame=Game()
    agame.run()
