#!/usr/bin/env python3
import time as t

cat=""" 
          ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄         
        ▄▀            ▄       ▀▄       
        █  ▄    ▄              █       
        █            ▄█▄▄  ▄   █ ▄▄▄   
 ▄▄▄▄▄  █      ▀    ▀█  ▀▄     █▀▀ ██  
 ██▄▀██▄█   ▄       ██    ▀▀▀▀▀    ██  
  ▀██▄▀██        ▀ ██▀             ▀██ 
    ▀████ ▀    ▄   ██   ▄█    ▄ ▄█  ██ 
       ▀█    ▄     ██    ▄   ▄  ▄   ██ 
       ▄█▄           ▀▄  ▀▀▀▀▀▀▀▀  ▄▀  
      █▀▀█████████▀▀▀▀████████████▀    
      ████▀  ███▀      ▀███  ▀██▀      
                                       
"""

while True:
    try:
        print("Nyan", end=' ')
    except(KeyboardInterrupt):
        try:
            print(cat)
            t.sleep(1)
            continue
        except(KeyboardInterrupt):
            continue
    except(EOFError):
        print(cat)
        t.sleep(1)
        continue

